[[redirects]]
  from = "/"
  to = "/#"
  status = 303
  force = false

[[redirects]]
from = "/afiles/other_logos/ia-logo-150x150.png"
to = "/afiles/sf2a/other_logos/loader.gif"
status = 303
force = false

[[redirects]]
from = "/setup.txt"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/composer.lock"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/composer.json"
to = "/index.html"
status = 401
force = true

[[redirects]]
from = "/netlify.toml"
to = "/index.html"
status = 401
force = true

[[headers]]
  for = "/index.html"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/games.html"
    [headers.values]
    Access-Control-Allow-Origin = "*"